trigger:
  - main
  - develop

pool:
  vmImage: ubuntu-20.04

variables:
  buildConfiguration: Release
  workingDirectory: $(System.DefaultWorkingDirectory)/web

stages:
  - stage: Build
    displayName: Build
    jobs:
      - job: Build
        displayName: Build
        steps:
          - task: CmdLine@2
            name: Install
            displayName: Install Packages
            inputs:
              script: 'npm install'
              workingDirectory: '$(workingDirectory)'
              failOnStderr: false
          
          - task: CmdLine@2
            name: BuildDev
            displayName: Create Build Artifact
            inputs:
              script: 'npm build'
              workingDirectory: '$(WebProjectRoot)'
              failOnStderr: true

          - task: ArchiveFiles@2
            name: ZipArtifactsDev
            displayName: Zip and Copy
            inputs:
              rootFolderOrFile: '$(WebProjectRoot)/build'
              archiveFile: '$(Build.ArtifactStagingDirectory)/deployment.zip'
              includeRootFolder: false
    
  - stage: Deployment
    displayName: 'Deploy to Development Environment'
    dependsOn: Build
    jobs:
    - job: DeployArtifact
      steps:
        - task: DownloadBuildArtifacts@0
          displayName: 'Download Build Artifacts'
          inputs:
            artifactName: 'WebDrop'
             
        - task: AzureRmWebAppDeployment@4
          displayName: 'Deploy artifact to Azure App Service'
          inputs:
            ConnectedServiceName: $(Development.Azure.SubscriptionName)
            WebAppName: $(Development.Azure.WebAppName)
            Package: "$(System.ArtifactsDirectory)/WebDrop/deployment.zip"
            UseWebDeploy: true
            TakeAppOfflineFlag: false
            RenameFilesFlag: false