version: "3"

services:
  poc_web:
    container_name: poc_web
    image: poc_web
    build:
      context: .
    restart: always
    ports:
      - "3000:80"
    environment:
      - "API_URL=production.example.com"
